/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Ignore;
import org.junit.Test;

public class LibraryTest {
    @Test
    @Ignore
    /* Case 1 */
    public void seller_sells_item_with_shipping_its_fee_is_percentage_3_point_5() {
    }

    @Test
    @Ignore
    /* Case 1 with different amount */
    public void seller_sells_item_with_shipping_different_mount_its_fee_is_percentage_3_point_5() {
    }

    @Test
    /* Case 2 */
    public void seller_sells_item_which_price_is_bigger_than_1000_it_is_charged_based_on_item_value_by_percentage_2() {
    }

    @Test
    /* Case 3 */
    public void seller_sells_item_durring_black_friday_it_is_charged_5_first_10_second_and_so_on() {
    }

}
